#pragma once

#include <vector>

#include "core/Rng.h"
#include "map/MapNode.h"

namespace bb {

/// The branching route through a run.
///
/// A layered graph: rows stacked from the start up to a single boss, with edges
/// only ever going one row up. Generated by walking a handful of routes from the
/// bottom and keeping whatever they touch, which is what produces forks that
/// merge again rather than a full lattice where every choice stays open.
///
/// Commitment is the point. Picking a branch should close some doors for a few
/// rows, or the map is decoration rather than a decision.
class RunMap {
public:
    /// Builds a map. `rows` includes the boss row, which always holds exactly
    /// one node.
    static RunMap Generate(Rng& rng, int rows, int width, int paths);

    const std::vector<MapNode>& Nodes() const noexcept { return nodes_; }
    const MapNode& Node(int index) const { return nodes_[static_cast<std::size_t>(index)]; }
    int NodeCount() const noexcept { return static_cast<int>(nodes_.size()); }
    int RowCount() const noexcept { return rows_; }

    /// Node indices on a row, ordered left to right.
    std::vector<int> NodesInRow(int row) const;

    /// Where you may go next.
    ///
    /// Pass -1 for "not on the map yet", which yields the whole opening row.
    std::vector<int> OptionsFrom(int index) const;

    /// The boss node -- the only node on the top row.
    int BossIndex() const;

private:
    std::vector<MapNode> nodes_;
    int rows_ = 0;
};

}  // namespace bb
